cli.config:
  # entity manager of doctrine
  entityManager: 'emSuite'
  # namespace for doctrine connection class
  namespace: '\Infrastructure\Resource\AppDB'

# config/packages/doctrine.yaml
doctrine:
  dbal:
    types:
    #      uuid: Ramsey\Uuid\Doctrine\UuidType
    connections:
      #template for params
      defaultDB:
        driver: '%env(DB_CONNECTION)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        charset: ~
        path: ~
        memory: ~
        # The unix socket to use for MySQL
        unix_socket: ~
        # True to use as persistent connection for the ibm_db2 driver
        persistent: ~
        # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
        protocol: ~
        # True to use dbname as service name instead of SID for Oracle
        service: ~
        # The session mode to use for the oci8 driver
        sessionMode: ~
        # True to use a pooled server with the oci8 driver
        pooled: ~


      #galaxyIdentity
      identity:
        driver: '%env(DB_CONNECTION)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_NAME_IDENTITY)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        charset: ~
        path: ~
        memory: ~
        # The unix socket to use for MySQL
        unix_socket: ~
        # True to use as persistent connection for the ibm_db2 driver
        persistent: ~
        # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
        protocol: ~
        # True to use dbname as service name instead of SID for Oracle
        service: ~
        # The session mode to use for the oci8 driver
        sessionMode: ~
        # True to use a pooled server with the oci8 driver
        pooled: ~

  orm:
    #comment if you don't need these custom functions in your dql
    dql:
      datetime_functions:
        date: Oro\ORM\Query\AST\Functions\SimpleFunction
        time: Oro\ORM\Query\AST\Functions\SimpleFunction
        timestamp: Oro\ORM\Query\AST\Functions\SimpleFunction
        convert_tz: Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
      numeric_functions:
        timestampdiff: Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
        dayofyear: Oro\ORM\Query\AST\Functions\SimpleFunction
        dayofmonth: Oro\ORM\Query\AST\Functions\SimpleFunction
        dayofweek: Oro\ORM\Query\AST\Functions\SimpleFunction
        week: Oro\ORM\Query\AST\Functions\SimpleFunction
        day: Oro\ORM\Query\AST\Functions\SimpleFunction
        hour: Oro\ORM\Query\AST\Functions\SimpleFunction
        minute: Oro\ORM\Query\AST\Functions\SimpleFunction
        month: Oro\ORM\Query\AST\Functions\SimpleFunction
        quarter: Oro\ORM\Query\AST\Functions\SimpleFunction
        second: Oro\ORM\Query\AST\Functions\SimpleFunction
        year: Oro\ORM\Query\AST\Functions\SimpleFunction
        sign: Oro\ORM\Query\AST\Functions\Numeric\Sign
        pow: Oro\ORM\Query\AST\Functions\Numeric\Pow
        round: Oro\ORM\Query\AST\Functions\Numeric\Round
        ceil: Oro\ORM\Query\AST\Functions\SimpleFunction
      string_functions:
        md5: Oro\ORM\Query\AST\Functions\SimpleFunction
        group_concat: Oro\ORM\Query\AST\Functions\String\GroupConcat
        concat_ws: Oro\ORM\Query\AST\Functions\String\ConcatWs
        cast: Oro\ORM\Query\AST\Functions\Cast
        replace: Oro\ORM\Query\AST\Functions\String\Replace
        date_format: Oro\ORM\Query\AST\Functions\String\DateFormat