cli.config:
  # entity manager of doctrine
  entityManager: 'emSuite'
  # namespace for doctrine connection class
  namespace: '\Infrastructure\Resource\AppDB'

# config/packages/doctrine.yaml
doctrine:
  dbal:
    types:
    #      uuid: Ramsey\Uuid\Doctrine\UuidType
    connections:
      #template for params
      defaultDB:
        driver: '%env(DB_CONNECTION)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        charset: ~
        path: ~
        memory: ~
        # The unix socket to use for MySQL
        unix_socket: ~
        # True to use as persistent connection for the ibm_db2 driver
        persistent: ~
        # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
        protocol: ~
        # True to use dbname as service name instead of SID for Oracle
        service: ~
        # The session mode to use for the oci8 driver
        sessionMode: ~
        # True to use a pooled server with the oci8 driver
        pooled: ~


      #galaxyIdentity
      identity:
        driver: '%env(DB_CONNECTION)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_NAME_IDENTITY)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        charset: ~
        path: ~
        memory: ~
        # The unix socket to use for MySQL
        unix_socket: ~
        # True to use as persistent connection for the ibm_db2 driver
        persistent: ~
        # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
        protocol: ~
        # True to use dbname as service name instead of SID for Oracle
        service: ~
        # The session mode to use for the oci8 driver
        sessionMode: ~
        # True to use a pooled server with the oci8 driver
        pooled: ~

  orm: