header:
  allowed_domains: [ 'http://127.0.0.1',
                     'https://localhost', ]
  allowed_methods: [ 'GET','POST','PUT','DELETE','OPTIONS' ]
  allowed_headers: [ 'AccountKey','x-requested-with', 'Content-Type', 'Origin', 'Authorization', 'Accept', 'Client-Security-Token', 'Host', 'Date', 'Cookie', 'Cookie2' ]
  allow_credentials: true,
  max_cache_age: 60
enableProdMode: true